const categories = [
  { id: 1, name: "A Boy's Name", spicy: false },
  { id: 2, name: "A Girl's Name", spicy: false },
  { id: 3, name: "Animals", spicy: false },
  { id: 4, name: "Fruits", spicy: false },
  { id: 5, name: "Vegetables", spicy: false },
  { id: 6, name: "Things in a Kitchen", spicy: false },
  { id: 7, name: "TV Shows", spicy: false },
  { id: 8, name: "Movies", spicy: false },
  { id: 9, name: "Countries", spicy: false },
  { id: 10, name: "Cities", spicy: false },
  { id: 11, name: "Sports", spicy: false },
  { id: 12, name: "Things That Are Cold", spicy: false },
  { id: 13, name: "Things That Are Hot", spicy: false },
  { id: 14, name: "School Subjects", spicy: false },
  { id: 15, name: "Occupations", spicy: false },
  { id: 16, name: "Things at a Beach", spicy: false },
  { id: 17, name: "Musical Instruments", spicy: false },
  { id: 18, name: "Things You Plug In", spicy: false },
  { id: 19, name: "Desserts", spicy: false },
  { id: 20, name: "Colors", spicy: false },
  { id: 21, name: "Car Brands", spicy: false },
  { id: 22, name: "Things in a Bathroom", spicy: false },
  { id: 23, name: "Types of Drinks", spicy: false },
  { id: 24, name: "Things in a Park", spicy: false },
  { id: 25, name: "Clothing Items", spicy: false },
  { id: 26, name: "Things That Fly", spicy: false },
  { id: 27, name: "Restaurant Foods", spicy: false },
  { id: 28, name: "Things in a Hospital", spicy: false },
  { id: 29, name: "Book Titles", spicy: false },
  { id: 30, name: "Things Made of Wood", spicy: false },
  { id: 31, name: "Things in a Toolbox", spicy: false },
  { id: 32, name: "Breakfast Foods", spicy: false },
  { id: 33, name: "Things You Sit On", spicy: false },
  { id: 34, name: "Flowers", spicy: false },
  { id: 35, name: "Insects", spicy: false },
  { id: 36, name: "Things at a Wedding", spicy: false },
  { id: 37, name: "Famous People", spicy: false },
  { id: 38, name: "Song Titles", spicy: false },
  { id: 39, name: "Things at a Carnival", spicy: false },
  { id: 40, name: "Things You Wear on Your Head", spicy: false },

  { id: 41, name: "Excuses for Being Late", spicy: true },
  { id: 42, name: "Things You Shouldn't Do at Work", spicy: true },
  { id: 43, name: "Bad First Date Ideas", spicy: true },
  { id: 44, name: "Things You'd Find in a Haunted House", spicy: true },
  { id: 45, name: "Things That Smell Bad", spicy: true },
  { id: 46, name: "Weird Hobbies", spicy: true },
  { id: 47, name: "Things You'd Say to an Alien", spicy: true },
  { id: 48, name: "Celebrity Nicknames", spicy: true },
  { id: 49, name: "Things a Pirate Would Say", spicy: true },
  { id: 50, name: "Reasons to Call in Sick", spicy: true },
  { id: 51, name: "Things That Are Overrated", spicy: true },
  { id: 52, name: "Things You Do When Nobody's Watching", spicy: true },
  { id: 53, name: "Bad Superpowers", spicy: true },
  { id: 54, name: "Things You'd Find in a Time Capsule", spicy: true },
  { id: 55, name: "Pickup Lines", spicy: true },
  { id: 56, name: "Things You Regret Buying", spicy: true },
  { id: 57, name: "Things a Villain Would Say", spicy: true },
  { id: 58, name: "Ways to Annoy Your Roommate", spicy: true },
  { id: 59, name: "Things You'd Ban If You Were President", spicy: true },
  { id: 60, name: "Terrible Band Names", spicy: true },
];

module.exports = categories;
